# --- AncientScrolls plugin configuration ---
# Fields marked with "FIXED" will not be discretely reloaded using /asreload and require a restart to reload
item:
  scroll:
    # FIXED
    # Maximum amount of scrolls each player can equip at once
    # min: 1, max: 54
    max-equipped-scrolls: 9
  generation:
    enabled: true
    # Scales the generation probability of Ancient Scrolls items generating in loot tables, vaults, and ominous vaults
    probability-scalar: 1.0
npc:
  generation:
    enabled: true
    # Scales the spawning probability of a NPC
    probability-scalar: 1.0
structure:
  generation:
    enabled: true
    # Scales the generation probability for structures
    probability-scalar: 1.0
